### ISSUE TITLE
No status reply

### ISSUE THREAD

**Issue by DanyaSWorlD** [DogsTailFarmer/martin-binance#11]
Bot running in demo mode. Notification set each 5 minutes.

![изображение](https://user-images.githubusercontent.com/19343702/182792723-94687ed9-9081-41b7-b882-71cc79b3aed2.png)

No status reply except _OK_ message.

**Comment by DogsTailFarmer** [comment]
Can't replay this issue. Update to last version and try one more time, please.

**Comment by DogsTailFarmer** [comment]
fixed in v1.2.3
