### ISSUE TITLE
Stopped comand in last state when low RAM 

### ISSUE THREAD

**Issue by DanyaSWorlD** [DogsTailFarmer/martin-binance#14]
Bot not starting with state recovery after stopped by low memory

**Comment by DogsTailFarmer** [comment]
Hi!
This is the expected and correct reaction. If the strategy was "stopped" for various reasons, it cannot be restarted with the status restored. These ones don't make sense. In this case, check the log if it is necessary to adjust the settings and start again.
Regard's, Jerry.

**Comment by DogsTailFarmer** [comment]
Hi!
As an option, after the restart, inform about the 'stopped' state and request OK to continue the launch.

**Comment by DogsTailFarmer** [comment]
Fixed in v1.2.3
