### ISSUE TITLE
Pairs with overlapping currencies 

### ISSUE THREAD

**Issue by DanyaSWorlD** [DogsTailFarmer/martin-binance#22]
I would like to have ability to launch multiple pairs with overlapping currencies at one exchange. (ex: BTCUSDT+LTCUSDT+LUNCUSDT+etc)

Please make it possible

**Comment by DogsTailFarmer** [comment]
Hi! This is simply solved by using sub-accounts on all connected exchanges. Completion is difficult and impractical.

Regard's, Jerry.
