### ISSUE TITLE
Sort profit and profit rating by value in Grafana

### ISSUE THREAD

**Issue by DanyaSWorlD** [DogsTailFarmer/martin-binance#23]
It would be nice to see profit in sorted order ( from most profitable to lowest )

![изображение](https://user-images.githubusercontent.com/19343702/188283206-8524e7ec-8fa3-4d20-9685-abcdc0be266e.png)

Is it possible?

**Comment by DogsTailFarmer** [comment]
In current Grafana ver. it's not possible.
