### ISSUE TITLE
Doesn't work on bitfinex: trading rules, step_size restriction not applicable, check

### ISSUE THREAD

**Issue by DanyaSWorlD** [DogsTailFarmer/martin-binance#28]
Hi!

It's normal. Amount first grid order depend from step_size (trade rules for exchange/account/pair and may be different for test and real place - compare it) and some another parameters:

```Python
        if not additional_grid and not grid_update and not GRID_ONLY and PROFIT_MAX < 100:
            k_m = 1 - PROFIT_MAX / 100
            amount_first_grid = max(amount_min, (step_size * base_price / ((1 / k_m) - 1)) / base_price)
```
For what? It is important for the TP order to meet the specified maximum price step, no more PROFIT_MAX, the smaller the volume of the first order, the greater the price spread for the TP sale. Trading rules for the pair are requested from the exchange when the strategy is initiated.

_Originally posted by @DogsTailFarmer in https://github.com/DogsTailFarmer/martin-binance/issues/15#issuecomment-1231775593_

**Comment by DogsTailFarmer** [comment]
Hi!

For Bitfinex step_zise limit not applicable.

Fixed for Bitfinex in exchanges-wrapper 1.2.5

Was - step_size = min_qty
Became - step_zise = 0.00001
