### ISSUE TITLE
Pair do not start but shows as started

### ISSUE THREAD

**Issue by sashausb** [DogsTailFarmer/martin-binance#31]
**Environment (please complete the following information):**
 - Version 1.2.7
 - OS: win11
 - Mode STANDALONE

**Describe the bug**
When i start bot it shows as it started but no orders and weird behavior

**To Reproduce**
Basic trade parameters:
- exchange: Binance
- pair: XRPBNB

**Expected behavior**
Expect bot to open orders

[2022-09-25 02:14:14,783: INFO] gRPC session started for client_id: 2093794251152
Python 3.8.5
Config found at C:\Users\sasha\AppData\Local\Packages\BED1B04E-C73B-45D2-BB43-2E8EB15322B6_j4y6f2x461yhe\LocalState\MartinBinance\config\ms_cfg.toml
Python 3.8.5
Config found at C:\Users\sasha\AppData\Local\Packages\BED1B04E-C73B-45D2-BB43-2E8EB15322B6_j4y6f2x461yhe\LocalState\MartinBinance\config\exch_srv_cfg.toml
Init Strategy, ver: 1.2.7 + 1.2.7 + 1.2.7
main.account_name: BinanceRus
[2022-09-25 02:15:17,320: INFO] gRPC session started for client_id: 2093794251152
main.exchange: binance
main.client_id: 2093794251152
main.srv_version: 1.2.5-1
main.restore_state: True
PRICE_FILTER: {'minPrice': '0.00000100', 'maxPrice': '1000.00000000', 'tickSize': '0.00000100'}
PERCENT_PRICE: {'multiplierUp': '5', 'multiplierDown': '0.2', 'avgPriceMins': 5}
LOT_SIZE: {'minQty': '1.00000000', 'maxQty': '9000000.00000000', 'stepSize': '1.00000000'}
MIN_NOTIONAL: {'minNotional': '0.05000000', 'applyToMarket': True, 'avgPriceMins': 5}
ICEBERG_PARTS: {'limit': 10}
MARKET_LOT_SIZE: {'minQty': '0.00000000', 'maxQty': '190214.38408304', 'stepSize': '0.00000000'}
MAX_NUM_ORDERS: {'maxNumOrders': 200}
================================================================
Base asset balance: {'asset': 'XRP', 'free': '0.0', 'locked': '0.0'}
Quote asset balance: {'asset': 'BNB', 'free': '0.25230193', 'locked': '0.00000000'}
================================================================
Init WSS, client_id: 2093794251152
Restore saved state after restart? Y:
25/09 02:15:27 Start Init section
25/09 02:15:27 BinanceRus, XRP/BNB. 
Round pattern, for base: 1, quote: 1.123456
Last ticker price:  0.001767
Press Enter for Start or Ctrl-Z for Cancel
25/09 02:15:32 Start
Start process for .db save
Start process for Telegram
Number of unreachable objects collected by GC: 57
25/09 02:15:32 Initial first: 0, second: 0.252301
25/09 02:15:32 Start Buy cycle with 0.25 BNB depo
25/09 02:15:32 
! =======================================
! debug output:
! sum_amount_first: 0, sum_amount_second: 0
! part_amount_first: 0, part_amount_second: 0
! initial_first: 0, initial_second: 0.252301
! initial_reverse_first: 0, initial_reverse_second: 0
! reverse_init_amount: 0
! reverse_target_amount: 0
! correction_amount_first: 0, correction_amount_second: 0
! tp_order: ()
! tp_part_amount_first: 0, tp_part_amount_second: 0
! profit_first: 0, profit_second: 0
! part_profit_first: 0, part_profit_second: 0
! deposit_first: 0.0, deposit_second: 0.25
! command: None
! reverse: False
! ======================================
25/09 02:15:32 place_grid: buy_side: True, depo: 0.25, reverse_target_amount: 0, allow_grid_shift: True, additional_grid: False, grid_update: False
25/09 02:15:32 set_trade_conditions: buy_side: True, depo: 0.250000, base_price: 0.001759, reverse_target_amount: 0, amount_min: 29, step_size: 1.0, delta_min: 0.000001
25/09 02:15:32 set_trade_conditions: depo: 0.250000, order_q: 12, amount_first_grid: 133, amount_2: 31.9, q_max: 0, coarse overprice: 3.730877
25/09 02:15:32 For Buy cycle set 1 order
25/09 02:15:32 Total grid amount: first: 0, second: 0
25/09 02:15:32 Shift grid threshold: 0.0018
25/09 02:17:12 Complete 0 buy cycle and 0 sell cycle
For all cycles profit:
First: 0
Second: 0
Summary: 0.000000
*** Shift grid mode ***
Buy cycle with 0 buy and 0 sell active orders.
No hold grid orders
Over price: 3.73%
Last ticker price: 0.001769
ver: 1.2.7+1.2.7+1.2.7
From start 0:01:40
WSS status: 0s

**Comment by DogsTailFarmer** [comment]
Hi!

The base reason it is too small deposit amount. And as Hot fix for #30 temp disabled initial check for depo volume. When it will be fixed in this situation strategy will give a warning about an unacceptably small deposit amount and will not start.

Regard's, Jerry.

**Comment by sashausb** [comment]
The main point it works fine on previous versions

вс, 25 сент. 2022 г., 11:26 Jerry ***@***.***>:
