### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by Hulkstance** [DogsTailFarmer/martin-binance#33]
Could you please provide another way of real-time communication e.g. discord, linkedin or anything else?

I don't know Python but by recovery after any reason crash, restart etc. you mean it's using event sourcing to keep track of the changes as well as a persistent store (sqlite)?

**Comment by DogsTailFarmer** [comment]
Hi! I will choose a platform for communication soon, but I will not be able to provide online support.

For saving op status used files in /.MartinBinance/last_state/ folder. State saved every 2 sec.

Regard's, Jerry

**Comment by DogsTailFarmer** [comment]
You can use [discussion area](https://github.com/DogsTailFarmer/martin-binance/discussions/categories/announcements) for free form QA.
