### ISSUE TITLE
Support for Binance.us

### ISSUE THREAD

**Issue by coltac** [DogsTailFarmer/martin-binance#44]
**Is your feature request related to a problem? Please describe.**
As a US resident, the exchanges are limited for us with Martin-Binance.

**Describe the solution you'd like**
Id like support for Binance-US exchange. Id be happy to do testing for the creator with my binanceUS api keys

**Describe alternatives you've considered**
Possibly a different US based exchange

**Additional context**

**Comment by DogsTailFarmer** [comment]
Hi!

I did some changes, but can't test it. Below instructions for update and test it.

- update exchanges-wrapper: ```pip install exchanges-wrapper==1.2.8b1```
- from ```exchanges_wrapper/exch_srv_cfg.toml.template``` copy to the ``` /.MartinBinance/config/exch_srv_cfg.toml``` two new sections: ```[endpoint.binance_us]``` and ```# Binance.us accounts```

 _*indentation and formatting matters*_

like this:

![image](https://user-images.githubusercontent.com/77513676/209940718-6af49f88-f54e-4674-aa40-30e597188d79.png)

- at ```/.MartinBinance/config/exch_srv_cfg.toml``` in ```exchange[]``` list to end add new row: ``` "Binance US",       # 11```, like as this:

![image](https://user-images.githubusercontent.com/77513676/209940356-1efbd7cd-612e-4fb7-8359-5a0817330474.png)

the id value (11) is incremented sequentially, there will be another. Specify this value in the file name cli_?_AAABBB.py and inside the value ex. ID_EXCHANGE = ?

Try starting. If there are errors - write within this task, if everything is fine - I will make a release.

Regard's, Jerry.

**Comment by coltac** [comment]
I will do some testing after work today, and let you know.  Thank you very much.  Im curious what you changed that i didnt when i was attempting this.

**Comment by DogsTailFarmer** [comment]
Compare exchanges-wrapper/exch_srv.py

**Comment by coltac** [comment]
It seems to have worked.  I did get 1 websocket error at the start of the bot, and i also had to Manually change the websocket URL in client.py in the exchanges-wrapper folder.  It remained at binance.us/9443 or whatever.  So far its working as intended on binance.US other than that.  It never did shift the grid, but im not sure that it needed to, so im not quite sure if that part of it works, but im guesing that it does.  Thank you.

**Comment by DogsTailFarmer** [comment]
coltrac, hi! It's good news, thanks for feedback.  Settings ws endpoint at ```client.py``` this is an legacy, I will remove it.
Merry Christmas and Happy New Year!

Regard's, Jerry.
