### ISSUE TITLE
Docker. Unable to find image 'martin-binance:latest' locally

### ISSUE THREAD

**Issue by Rocky-04** [DogsTailFarmer/martin-binance#46]
Hello, I am trying to use the ghcr.io/dogstailfarmer/martin-binance:latest from your repository, but I am encountering an error when running the command 

docker run --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/__init__.py" > init.py && \
  docker run --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/ms_cfg.toml.template" > ms_cfg.toml.template &&\
  docker run --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/funds_rate.db.template" > funds_rate.db.template &&\
  docker run --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/cli_0_BTCUSDT.py.template" > cli_0_BTCUSDT.py.template &&\
  docker run --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/cli_2_AAABBB.py.template" > cli_2_AAABBB.py.template &&\
  python3 init.py && rm init.py && rm ms_cfg.toml.template && rm funds_rate.db.template && rm cli_0_BTCUSDT.py.template && rm cli_2_AAABBB.py.template

I get the error message:
'Unable to find image 'martin-binance:latest' locally
docker: Error response from daemon: pull access denied for martin-binance, repository does not exist or may require 'docker login': denied: requested access to the resource is denied."

I have followed all the steps provided in the instructions, including pulling the latest version of the image using the command 'docker pull ghcr.io/dogstailfarmer/martin-binance:latest'. Can you please help me understand what might be causing this error and how to resolve it? 

Thank you.

**Comment by Rocky-04** [comment]
I was able to successfully tag the Docker image using the command 
"docker image tag ded931a683e2 martin-binance".

 However, when I tried to run the command
  "docker run -itP --mount type=bind,source=/home/ubuntu/.MartinBinance,target=/home/appuser/.MartinBinance,readonly=false --network=host --restart=always --name=0- BTCUSDT --user=root martin-binance /home/appuser/.MartinBinance/cli_0_BTCUSDT.py 1", 
  
  I received the error
   "exec /home/appuser/.MartinBinance/cli_0_BTCUSDT.py: exec format error". 
   
   I was wondering if you could provide any guidance on how to resolve this issue. Thank you for your time and for creating such a great repository.

**Comment by DogsTailFarmer** [comment]
Hi!

What OS are you used? This command example for Ubuntu

```terminal
(venv) (base) ubuntu@ubuntu:~/PycharmProjects/martin-binance$ docker run --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/__init__.py" > init.py && \
  docker run --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/ms_cfg.toml.template" > ms_cfg.toml.template &&\
  docker run --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/funds_rate.db.template" > funds_rate.db.template &&\
  docker run --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/cli_0_BTCUSDT.py.template" > cli_0_BTCUSDT.py.template &&\
  docker run --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/cli_2_AAABBB.py.template" > cli_2_AAABBB.py.template &&\
  python3 init.py && rm init.py && rm ms_cfg.toml.template && rm funds_rate.db.template && rm cli_0_BTCUSDT.py.template && rm cli_2_AAABBB.py.template
Python 3.10.6
Config found at /home/ubuntu/.MartinBinance/config/ms_cfg.toml
(venv) (base) ubuntu@ubuntu:~/PycharmProjects/martin-binance$ docker run -itP \
 --mount type=bind,source=/home/ubuntu/.MartinBinance,target=/home/appuser/.MartinBinance \
 --network=host \
 --restart=always \
 --name=0-BTCUSDT \
 martin-binance \
 /home/appuser/.MartinBinance/cli_0_BTCUSDT.py 1
Python 3.10.6
Config found at /home/appuser/.MartinBinance/config/ms_cfg.toml
Python 3.10.6
Config found at /home/appuser/.MartinBinance/config/exch_srv_cfg.toml
Init Strategy, ver: 1.2.7 + 1.2.13-3 + 1.2.13
main.account_name: Demo - OKX
```
and must be modified for Win and osx.

**Comment by DogsTailFarmer** [comment]
Also check you path.

Regard's, Jerry.

**Comment by Rocky-04** [comment]
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-29-generic x86_64)

root@vpsyeune:~# docker run --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/__init__.py" > init.py && \
>   docker run --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/ms_cfg.toml.template" > ms_cfg.toml.template &&\
 -c "cat ./martin_bina>   docker run --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/funds_rate.db.template" > funds_rate.db.template &&\
>   docker run --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/cli_0_BTCUSDT.py.template" > cli_0_BTCUSDT.py.template &&\
rm --entrypoint /bin/sh martin-b>   docker run --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/cli_2_AAABBB.py.template" > cli_2_AAABBB.py.template &&\
 init.py && rm>   python3 init.py && rm init.py && rm ms_cfg.toml.template && rm funds_rate.db.template && rm cli_0_BTCUSDT.py.template && rm cli_2_AAABBB.py.template
Python 3.10.9
Config found at /root/.MartinBinance/config/ms_cfg.toml
root@vpsyeune:~# docker run -itP \
>  --mount type=bind,source=/home/ubuntu/.MartinBinance,target=/home/appuser/.MartinBinance \
>  --network=host \
>  --restart=always \
>  --name=0-BTCUSDT \
>  martin-binance \
>  /home/appuser/.MartinBinance/cli_0_BTCUSDT.py 1
exec /home/appuser/.MartinBinance/cli_0_BTCUSDT.py: exec format error

**Comment by DogsTailFarmer** [comment]
Hi!

Next step, your working path is ```/root/.MartinBinance/config/ms_cfg.toml```, but in second command used ```source=/home/ubuntu/.MartinBinance```. Try change it.

Jerry.

**Comment by Rocky-04** [comment]
Hi! 

I attempted to change the working path, but it did not resolve the issue. I also tried running the command as the root user, but I encountered the same error. Are there any other suggestions or solutions I could try?

```
$ docker run --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/__init__.py" > init.py && \
  docker run > --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/ms_cfg.toml.template" > ms_cfg.toml.template &&\
  docker run > --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/funds_rate.db.template" > funds_rate.db.template &&\
 >  docker run --rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/cli_0_BTCUSDT.py.template" > cli_0_BTCUSDT.py.template &&\
  docker run --> rm --entrypoint /bin/sh martin-binance -c "cat ./martin_binance/cli_2_AAABBB.py.template" > cli_2_AAABBB.py.template &&\
 >  python3 init.py && rm init.py && rm ms_cfg.toml.template && rm funds_rate.db.template && rm cli_0_BTCUSDT.py.template && rm cli_2_AAABBB.py.template
 
Python 3.10.9
Config found at /home/rocky/.MartinBinance/config/ms_cfg.toml

$ docker run -itP \
 --mo> unt type=bind,source=/home/rocky/.MartinBinance,target=/home/appuser/.MartinBinance \
 --net> work=host \
 --r> estart=always \
>  --name=0-BTCUSDT5555 \
 > martin-binance \
 /home/> appuser/.MartinBinance/cli_0_BTCUSDT.py 1
 ``
exec /home/appuser/.MartinBinance/cli_0_BTCUSDT.py: exec format err
```

**Comment by DogsTailFarmer** [comment]
Ok, i think i found a error, shebang on the entrypoint in cli_0_BTCUSDT.py

```#!/usr/bin/env python3``` really its path to my develop environment on local, but not Python from docker image.

You can try change it to your local Python path, its not correct, but as hot fix resolve this issue. IMHO.

I fix this bug shortly.

Regard's, Jerry.

**Comment by DogsTailFarmer** [comment]
Hi!

Can you test ```#! /usr/local/bin/python3``` as shebang on the ```/home/rocky/.MartinBinance/cli_0_BTCUSDT.py``` ?

Its work for both with correct Python ver. and have not problem with "/usr/local/bin/: bad interpreter: Permission denied" error for both - in PyCharm console:
``` 
/home/ubuntu/PycharmProjects/martin-binance/venv/bin/python /home/ubuntu/.MartinBinance/cli_0_BTCUSDT.py 
Python 3.10.6
Config found at /home/ubuntu/.MartinBinance/config/ms_cfg.toml
Python 3.10.6
Config found at /home/ubuntu/.MartinBinance/config/exch_srv_cfg.toml
*/home/ubuntu/PycharmProjects/martin-binance/venv/bin/python*
Init Strategy, ver: 1.2.7 + 1.2.13-4 + 1.2.13-4
main.account_name: Demo - OKX
```
and for docker image:

```
(venv) (base) ubuntu@ubuntu:~/PycharmProjects/martin-binance$ docker run -itP  --mount type=bind,source=/home/ubuntu/.MartinBinance,target=/home/appuser/.MartinBinance  --network=host  --restart=always  --name=0-BTCUSDT  martin-binance  /home/appuser/.MartinBinance/cli_0_BTCUSDT.py 1
Python 3.10.6
Config found at /home/appuser/.MartinBinance/config/ms_cfg.toml
Python 3.10.6
Config found at /home/appuser/.MartinBinance/config/exch_srv_cfg.toml
*/usr/local/bin/python3*
Init Strategy, ver: 1.2.7 + 1.2.13-3 + 1.2.13
main.account_name: Demo - OKX
```

Regard's, Jerry.

**Comment by Rocky-04** [comment]
Hi Jerry,

Unfortunately, the shebang line you provided didn't help. However, the issue was probably due to my misconfiguration. I created a user named "ubuntu" and after re-executing the commands as instructed, everything worked.

Thanks for your help and for considering my question. I apologize for wasting your time. Your project is very cool and I appreciate your efforts.

Best regards,
Oleg

**Comment by DogsTailFarmer** [comment]
Thank you. In production, I do not use docker, now I see what needs to be fixed.

All the best, Jerry.
