### ISSUE TITLE
Error with SHIBA

### ISSUE THREAD

**Issue by bizkut** [DogsTailFarmer/martin-binance#5]
Hi, I got this error when try to start with SHIBA with second currency 200 USDT

`07/02 12:11:17 place_grid: buy_side:True, depo: 200.0, reverse_target_amount: None, allow_grid_shift: True
07/02 12:11:17 set_trade_conditions: buy_side: True, depo: 200.0, base_price: 2.8195895e-05, reverse_target_amount: None, amount_min: 354662, delta_min: 1e-08
07/02 12:11:17 bollinger_band: tbb=3.072651478610889e-05, bbb=1.996248521389111e-05
07/02 12:11:17 For Buy cycle set 10 orders for 29.20% over price
07/02 12:11:17 Send order id:1 for BUY 563862.0 by 2.82e-05 = 15.900908
07/02 12:11:17 Send order id:2 for BUY 602524.0 by 2.771e-05 = 16.695940
07/02 12:11:17 Send order id:3 for BUY 644987.0 by 2.718e-05 = 17.530747
07/02 12:11:17 Send order id:4 for BUY 692263.0 by 2.659e-05 = 18.407273
07/02 12:11:17 Send order id:5 for BUY 745378.0 by 2.593e-05 = 19.327652
07/02 12:11:17 Shift grid threshold: 0.00
07/02 12:11:17 Create limit order exception: <AioRpcError of RPC that terminated with:
       status = StatusCode.UNKNOWN
       details = "Unexpected <class 'binance.errors.BinanceError'>: Invalid price."
       debug_error_string = "{"created":"@1644207077.325872810","description":"Error received from peer ipv6:[::1]:50051","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Unexpected <class 'binance.errors.BinanceError'>: Invalid price.","grpc_status":2}"
>
07/02 12:11:17 Create limit order exception: <AioRpcError of RPC that terminated with:
       status = StatusCode.UNKNOWN
       details = "Unexpected <class 'binance.errors.BinanceError'>: Invalid price."
       debug_error_string = "{"created":"@1644207077.329569101","description":"Error received from peer ipv6:[::1]:50051","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Unexpected <class 'binance.errors.BinanceError'>: Invalid price.","grpc_status":2}"
>`

**Comment by DogsTailFarmer** [comment]
Hi! by 2.82e-05  very very small price is converted to e-05 and the exchange does not accept the price in this format. Try another pair.
