### ISSUE TITLE
Bitfinex Internal Server Errror

### ISSUE THREAD

**Issue by Lexus083** [DogsTailFarmer/martin-binance#69]
Windows 7
Standalone
Bitfinex
Tell me why I have this error.

![error](https://github.com/DogsTailFarmer/martin-binance/assets/40821654/bd568f1b-823b-43c8-ac08-33207ceaad26)

**Comment by DogsTailFarmer** [comment]
Hello! You can try upgrading app to the latest version. Attention, all config and pair settings must be updated, use templates.
Regards, Jerry.

**Comment by DogsTailFarmer** [comment]
![image](https://github.com/DogsTailFarmer/martin-binance/assets/77513676/14ea1f07-1564-454d-bba6-1123dea79cbd)
And also you can some trouble into `fund_rate.db`, try take clear .db from template.

**Comment by Lexus083** [comment]
Thank you. It only worked after I deleted everything and started all over again.
