### ISSUE TITLE
error when launching strategy

### ISSUE THREAD

**Issue by Lexus083** [DogsTailFarmer/martin-binance#76]
[2024-04-27 09:24:05,755: INFO] gRPC session started for client_id: 63285328
trade_id: gHt8aRaFtLqbF2Ur3Nttjk
[2024-04-27 09:24:08,971: DEBUG] Exception on send request <grpc.aio._channel.UnaryUnaryMultiCallable object at 0x0000000007EE01C0>: UNKNOWN, Unexpected <class 'google.protobuf.json_format.ParseError'>: Message type "martin.FetchExchangeInfoSymbolResponse" has no field named "otoAllowed" at "FetchExchangeInfoSymbolResponse".
 Available Fields(except extensions): "['symbol', 'status', 'baseAsset', 'baseAssetPrecision', 'quoteAsset', 'quotePrecision', 'quoteAssetPrecision', 'baseCommissionPrecision', 'quoteCommissionPrecision', 'orderTypes', 'icebergAllowed', 'ocoAllowed', 'quoteOrderQtyMarketAllowed', 'allowTrailingStop', 'cancelReplaceAllowed', 'isSpotTradingAllowed', 'isMarginTradingAllowed', 'filters', 'permissions', 'defaultSelfTradePreventionMode', 'allowedSelfTradePreventionModes']"

**Comment by DogsTailFarmer** [comment]
Hi! 

Add some info please:

ver:
exchange:

Regards, Jerry.

**Comment by Lexus083** [comment]
exchanges-wrapper 2.1.11
martin-binance 3.0.6
exchange: binance

Clean, new installation. Now another error: 
Start server
Run in terminal window
exchanges-wrapper-srv
Exeption:NotImplementedError.

**Comment by Lexus083** [comment]
martin-binance       1.3.6.post1
exchanges-wrapper    1.3.7.post1
exchange: binance.com

**Comment by DogsTailFarmer** [comment]
Hi! It is really old version, try update, I have not this error on last
```
pip install -U martin-binance
```
Regards, Jerry.

**Comment by Lexus083** [comment]
pip install -U martin-binance
Requirement already satisfied: martin-binance in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (1.3.6.post1)

Available only martin-binance 1.3.6.post1

**Comment by DogsTailFarmer** [comment]
Try this
```
pip install martin-binance==3.0.6
```

**Comment by Lexus083** [comment]
Ready. Now another problem has appeared:
exchanges-wrapper-srv
Exception:
Traceback (most recent call last):
NotImplementedError

**Comment by DogsTailFarmer** [comment]
What OS are your used? Attach `exch_srv.log` with this error.

**Comment by Lexus083** [comment]
windows 10
[exch_srv.log](https://github.com/DogsTailFarmer/martin-binance/files/15142679/exch_srv.log)

**Comment by DogsTailFarmer** [comment]
This is a problem with implementing asyncio in a Windows environment. I tried several workarounds, but nothing helped. This version cannot run on Windows in the terminal. Alternatively you can use Docker - [install from Docker](https://github.com/DogsTailFarmer/martin-binance/wiki/Quick-start#docker)

**Comment by DogsTailFarmer** [comment]
> I installed Docker, but I don't understand what to do there.
> 
> 2024-04-29 15:20:51 Traceback (most recent call last): 2024-04-29 15:20:51 File "/home/appuser/.local/lib/python3.10/site-packages/exchanges_wrapper/exch_srv.py", line 5, in 2024-04-29 15:20:51 from exchanges_wrapper import **version** as ver_ew 2024-04-29 15:20:51 ImportError: cannot import name '**version**' from 'exchanges_wrapper' (/home/appuser/.local/lib/python3.10/site-packages/exchanges_wrapper/**init**.py)

I confirm, I will do this as soon as possible.

Regards, Jerry

**Comment by DogsTailFarmer** [comment]
Hi!

## 3.0.7 - 2024-05-02
### Fix
* `Docker`: server-client deployment functionality restored (`exchanges-wrapper` and `martin-binance`), also for Windows
