### ISSUE TITLE
Not working controlls or status request onTG bot 

### ISSUE THREAD

**Issue by sashausb** [DogsTailFarmer/martin-binance#9]
Not working controlls or status request onTG bot 

When i sent (status) there no reply

**Comment by DogsTailFarmer** [comment]
Hi!

Example of use. After sending request there may be a slight delay up to 10s before get response.


https://user-images.githubusercontent.com/77513676/180641065-759c16f8-d1b7-4ed9-9feb-ed0a35727d22.mp4

Regards. Jerry.

**Comment by sashausb** [comment]
So why it couldn't understand command without reply ?
